//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLLLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhacCu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhacCu()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public string MaNC { get; set; }
        public string TenNC { get; set; }
        public string NhanHieu { get; set; }
        public string NamSanXuat { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MaLoaiNC { get; set; }
    
        public virtual LoaiNhacCu LoaiNhacCu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
